# Use an official OpenJDK runtime as a parent image
FROM openjdk:21
EXPOSE 8081



# Copy the JAR file from the host machine to the container
ADD target/spring-boot-docker.jar spring-boot-docker.jar

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "/spring-boot-docker.jar"]