# Use an official OpenJDK runtime as a parent image
FROM openjdk:21-jdk-alpine



# Copy the JAR file from the host machine to the container
COPY target/demo.jar app.jar

# Expose the application port
EXPOSE 8081

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]